module.exports = async (req, res) => {
var names = {
    "female" : [
      "Saanvi",
      "Anya",
      "Aadhya",
      "Aaradhya",
      "Ananya",
      "Pari",
      "Anika",
      "Navya",
      "Angel",
      "Diya",
      "Myra",
      "Sara",
      "Iraa",
      "Ahana",
      "Anvi",
      "Prisha",
      "Riya",
      "Aarohi",
      "Anaya",
      "Akshara",
      "Eva",
      "Shanaya",
      "Kyra",
      "Siya"
    ],
    "male" : [
      "Aarav",
      "Vihaan",
      "Vivaan",
      "Ananya",
      "Diya",
      "Advik",
      "Kabir",
      "Anaya",
      "Aarav",
      "Vivaan",
      "Aditya",
      "Vivaan",
      "Vihaan",
      "Arjun",
      "Vivaan",
      "Reyansh",
      "Mohammed",
      "Sai",
      "Arnav",
      "Aayan",
      "Krishna",
      "Ishaan",
      "Shaurya",
      "Atharva",
      "Advik",
      "Pranav",
      "Advaith",
      "Aaryan",
      "Dhruv",
      "Kabir",
      "Ritvik",
      "Aarush",
      "Kian",
      "Darsh",
      "Veer"
    ],
    "surnames" : [
      "Bedi",
      "Gandhi",
      "Parekh",
      "Kohli",
      "Ahluwalia",
      "Chandra",
      "Jha",
      "Khanna",
      "Bajwa",
      "Chawla",
      "Lal",
      "Anand",
      "Gill",
      "Chakrabarti",
      "Dubey",
      "Kapoor",
      "Khurana",
      "Modi",
      "Kulkarni",
      "Khatri",
      "Kaur",
      "Dhillon",
      "Kumar",
      "Gupta",
      "Naidu",
      "Das",
      "Jain",
      "Chowdhury",
      "Dalal",
      "Thakur",
      "Gokhale",
      "Apte",
      "Sachdev",
      "Mehta",
      "Ganguly",
      "Bhasin",
      "Mannan",
      "Ahuja",
      "Singh",
      "Bakshi",
      "Basu",
      "Ray",
      "Mani",
      "Datta",
      "Balakrishna",
      "Biswas",
      "Laghari",
      "Malhotra",
      "Dewan",
      "Purohit"
    ]
  };

  var female = names.female;
  var male = names.male;
  var surnames = names.surnames;
  var fnf = female[Math.floor(Math.random() * 24)];
  var fnm = male[Math.floor(Math.random() * 35)];
  var ln = surnames[Math.floor(Math.random() * 50)];

  var resultf = fnf +" "+ ln;
  var resultm = fnm +" "+ ln;

  res.send({"female": resultf, 
                "male": resultm,
                })
}

